openapi: 3.0.0
info:
  title: RAG Chatbot Ingestion API
  version: 1.0.0
paths:
  /embed:
    post:
      summary: Generate embeddings for a given text
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                text:
                  type: string
                  description: The text content to embed
              required:
                - text
      responses:
        '200':
          description: Successful embedding generation
          content:
            application/json:
              schema:
                type: object
                properties:
                  embedding:
                    type: array
                    items:
                      type: number
                      format: float
                      description: A single float value from the embedding vector
                    description: The generated embedding vector
                required:
                  - embedding
        '400':
          description: Bad request (e.g., empty text)
        '403':
          description: Unauthorized
        '500':
          description: Internal server error
  /ingest:
    post:
      summary: Ingest document chunks into the vector database
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                source_file:
                  type: string
                  description: Path to the original document file
                chunks:
                  type: array
                  items:
                    type: object
                    properties:
                      chunk_id:
                        type: string
                        description: Unique ID for the chunk
                      content:
                        type: string
                        description: The text content of the chunk
                      heading:
                        type: string
                        description: Optional heading of the section
                      order_in_file:
                        type: integer
                        description: Order of the chunk within the file
                    required:
                      - chunk_id
                      - content
              required:
                - source_file
                - chunks
      responses:
        '200':
          description: Documents ingested successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: "success"
                  ingested_count:
                    type: integer
                    description: Number of chunks successfully ingested
                required:
                  - status
                  - ingested_count
        '400':
          description: Bad request (e.g., invalid chunk format)
        '403':
          description: Unauthorized
        '500':
          description: Internal server error
