openapi: 3.0.0
info:
  title: RAG Chatbot Query API
  version: 1.0.0
paths:
  /query:
    post:
      summary: Process a user query and return a grounded answer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                conversation_id:
                  type: string
                  format: uuid
                  description: Optional ID of an existing conversation
                user_id:
                  type: string
                  description: Identifier for the user
                query:
                  type: string
                  description: The user's natural language query
              required:
                - user_id
                - query
      responses:
        '200':
          description: Successful response with the chatbot's answer and citations
          content:
            application/json:
              schema:
                type: object
                properties:
                  answer:
                    type: string
                    description: The chatbot's grounded answer
                  citations:
                    type: array
                    items:
                      type: object
                      properties:
                        source_file:
                          type: string
                          description: Path to the source document
                        heading:
                          type: string
                          description: Heading of the relevant section
                        chunk_id:
                          type: string
                          description: ID of the retrieved chunk
                required:
                  - answer
                  - citations
        '400':
          description: Bad request (e.g., missing query)
        '403':
          description: Unauthorized (if API key/auth middleware is active)
        '500':
          description: Internal server error
  /selected-text:
    post:
      summary: Process a query with selected text context
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                conversation_id:
                  type: string
                  format: uuid
                  description: Optional ID of an existing conversation
                user_id:
                  type: string
                  description: Identifier for the user
                query:
                  type: string
                  description: The user's natural language query
                selected_text:
                  type: string
                  description: The text selected by the user for prioritized context
              required:
                - user_id
                - query
                - selected_text
      responses:
        '200':
          description: Successful response with the chatbot's answer and citations
          content:
            application/json:
              schema:
                type: object
                properties:
                  answer:
                    type: string
                    description: The chatbot's grounded answer
                  citations:
                    type: array
                    items:
                      type: object
                      properties:
                        source_file:
                          type: string
                          description: Path to the source document
                        heading:
                          type: string
                          description: Heading of the relevant section
                        chunk_id:
                          type: string
                          description: ID of the retrieved chunk
                required:
                  - answer
                  - citations
        '400':
          description: Bad request (e.g., missing query/selected text)
        '403':
          description: Unauthorized
        '500':
          description: Internal server error
  /health:
    get:
      summary: Health check endpoint
      responses:
        '200':
          description: API is healthy
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: "ok"
                required:
                  - status
        '500':
          description: Internal server error (e.g., database connection issues)
